CREATE SEQUENCE TBL_OCORRENCIA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_OCORRENCIA(
    ID INTEGER DEFAULT TBL_OCORRENCIA_SEQ.nextval NOT NULL,
    TIPO_OCORRENCIA VARCHAR(100) NOT NULL,
    DATA_OCORRENCIA DATE NOT NULL,
    STATUS VARCHAR2(100) NOT NULL,
    DESCRICAO VARCHAR2(600) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL
);