CREATE SEQUENCE SEQ_USUARIO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_USUARIO(
    ID_USUARIO INTEGER DEFAULT SEQ_USUARIO.nextval NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL
);