CREATE SEQUENCE TBL_LOCAL_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_LOCAL(
    ID_LOCAL INTEGER DEFAULT TBL_LOCAL_SEQ.nextval NOT NULL,
    CEP VARCHAR(100) NOT NULL,
    PRIORIDADE VARCHAR2(100) NOT NULL
);